server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /env-config.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location = /health {
        add_header Content-Type text/plain;
        add_header Access-Control-Allow-Origin "*";
        add_header Cache-Control "no-cache, no-store";
        return 200 "ok";
    }
}
